- name: Install and Configure Helm and Jenkins
  hosts: kubernetes_master
  become: yes
  tasks:

    - name: Install Helm
      get_url:
        url: https://get.helm.sh/helm-v3.9.4-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz

    - name: Extract Helm
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /usr/local/bin/
        remote_src: yes

    - name: Move Helm binary to /usr/local/bin
      command: mv /usr/local/bin/linux-amd64/helm /usr/local/bin/helm

    - name: Check Helm version
      command: helm version
      register: helm_version_output

    - debug:
        msg: "Helm version: {{ helm_version_output.stdout }}"
