- name: Install Helm and Jenkins
  hosts: master
  become: yes
  tasks:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh

    - name: Set permissions for Helm script
      file:
        path: /tmp/get_helm.sh
        mode: '0700'

    - name: Install Helm
      command: /tmp/get_helm.sh

    - name: Check Helm version
      command: helm version
      register: helm_version
      changed_when: false

    - name: Display Helm version
      debug:
        msg: "Helm version: {{ helm_version.stdout }}"

    - name: Add the Jenkins Helm repository
      command: helm repo add jenkins https://charts.jenkins.io

    - name: Update Helm repositories
      command: helm repo update

    - name: Create namespace for Jenkins
      command: kubectl create namespace jenkins
      ignore_errors: yes

    - name: Install Jenkins using Helm
      command: helm install jenkins jenkins/jenkins --namespace jenkins

    - name: Get Jenkins service URL
      command: kubectl get svc jenkins --namespace jenkins -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
      register: jenkins_service_url
      changed_when: false

    - name: Show Jenkins service URL
      debug:
        msg: "Jenkins URL: http://{{ jenkins_service_url.stdout }}"

    - name: Get Jenkins Admin password
      command: kubectl get secret --namespace jenkins jenkins-admin-token -o go-template='{{.data.token | base64decode}}'
      register: jenkins_admin_password
      changed_when: false

    - name: Show Jenkins Admin password
      debug:
        msg: "Jenkins Admin Password: {{ jenkins_admin_password.stdout }}"

